# Generated by Django 3.2.9 on 2021-11-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/%Y/%m/%d'),
        ),
    ]
