# Generated by Django 3.2.9 on 2021-12-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20211222_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='icon',
            field=models.ImageField(upload_to='static/image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=models.ImageField(upload_to='static/image/%Y/%m/%d'),
        ),
    ]
